[build]
builder = "DOCKERFILE"
dockerfilePath = "stellar.tpad/Dockerfile"
buildContext = "stellar.tpad"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
