export const CONTRACT_CONFIG = {
  token: process.env.NEXT_PUBLIC_TOKEN_CONTRACT_ID ?? '',
  bondingCurve: process.env.NEXT_PUBLIC_BONDING_CONTRACT_ID ?? '',
};

// Stellar network constants
export const XLM_NATIVE_CONTRACT = 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA'; // testnet
export const TREASURY_ADDRESS = 'GCZ2IR57HR7JSKNA5ILVGBWJSUFUHPJHW35RXDQ7HTDBZ2QHURULFP63';
export const BONDING_CURVE_CONTRACT = process.env.NEXT_PUBLIC_BONDING_CURVE_CONTRACT ?? '';
export const MINT_FEE_XLM = 1; // 1 XLM mint fee
export const TRADE_FEE_BPS = 100; // 1% = 100 basis points