[package]
name = "token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "22.0", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "22.0", features = ["testutils"] }
proptest = "1"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
codegen-units = 1
